language: rust
sudo: false
rust:
  - nightly
env:
  - RUSTFLAGS="-C target-feature=-sse -C target-feature=+x87" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+sse" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+sse2" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+sse3" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+ssse3" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+sse4a" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+sse4.1" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+sse4.2" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+avx" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+avx2" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-feature=+avx512" RUN="build --all --examples --tests --benches --bins"
  - RUSTFLAGS="-C target-cpu=pentium" RUN="test --lib --tests --benches --examples"
  - RUSTFLAGS="-C target-cpu=pentium3" RUN="test --lib --tests --benches --examples"
  - RUSTFLAGS="-C target-cpu=pentium4" RUN="test --lib --tests --benches --examples"
  - RUSTFLAGS="-C target-cpu=core2" RUN="test --lib --tests --benches --examples"
  - RUSTFLAGS="-C target-cpu=nehalem" RUN="test --lib --tests --benches --examples"
  - RUSTFLAGS="-C target-cpu=sandybridge" RUN="test --lib --tests --benches --examples"
  - RUSTFLAGS="-C target-cpu=native" RUN="test --lib --tests --benches --examples"
matrix:
  fast_finish: true
install:
script:
  - cat /proc/cpuinfo
  - bash -c "cargo $RUN --verbose --features \"no-std\""
  - bash -c "cargo $RUN --verbose"
notifications:
  email: false
