language: rust
sudo: false
rust:
  - nightly
env:
  - RUSTFLAGS="-C target-feature=+sse"
  - RUSTFLAGS="-C target-feature=+sse2"
  - RUSTFLAGS="-C target-feature=+sse3"
  - RUSTFLAGS="-C target-feature=+ssse3"
  - RUSTFLAGS="-C target-feature=+sse4a"
  - RUSTFLAGS="-C target-feature=+sse4.1"
  - RUSTFLAGS="-C target-feature=+sse4.2"
  - RUSTFLAGS="-C target-feature=+avx"
  - RUSTFLAGS="-C target-feature=+avx2"
  - RUSTFLAGS="-C target-feature=+avx512"
  - RUSTFLAGS="-C target-cpu=pentium3" RUN="true"
  - RUSTFLAGS="-C target-cpu=pentium4" RUN="true"
  - RUSTFLAGS="-C target-cpu=core2" RUN="true"
  - RUSTFLAGS="-C target-cpu=nehalem" RUN="true"
  - RUSTFLAGS="-C target-cpu=sandybridge" RUN="true"
  - RUSTFLAGS="-C target-cpu=native" RUN="true"
matrix:
  fast_finish: true
install:
  - cargo build
script:
  - cat /proc/cpuinfo
  - bash -c "[ $RUN == \"true\" ] && cargo test --verbose --all || true"
  - bash -c "[ $RUN == \"true\" ] && cargo bench --verbose --all || true"
notifications:
  email: false
cache: cargo
