[package]
name = "faster"
description = "Explicit SIMD for humans"
authors = ["Adam Niederer <adam.niederer@gmail.com>"]
repository = "https://github.com/AdamNiederer/faster"
license = "MPL-2.0"
version = "0.3.0"

[dependencies]
stdsimd = { git = "https://github.com/rust-lang-nursery/stdsimd", branch = "master" }

[features]
no-std = []

[dev-dependencies]

[profile.release]
opt-level = 3
debug = true
