[package]
name = "faster"
description = "Explicit SIMD for humans"
authors = ["Adam Niederer <adam.niederer@gmail.com>"]
license = "MPL-2.0"
version = "0.4.2"

keywords = ["simd"]
categories = ["no-std", "hardware-support", "api-bindings"]
documentation = "https://docs.adamniederer.com/faster/index.html"
repository = "https://github.com/AdamNiederer/faster"
readme = "README.org"

[dependencies]
stdsimd = "0.0.4"

[features]
no-std = []

[dev-dependencies]

[profile.release]
opt-level = 3
debug = true
