[package]
name = "faster"
description = "Explicit SIMD for humans"
authors = ["Adam Niederer <adam.niederer@gmail.com>"]
repository = "https://github.com/AdamNiederer/faster"
license = "MPL-2.0"
version = "0.2.1"

[dependencies]
stdsimd = "0.0.3"

[profile.release]
opt-level = 3
debug = true
